config/routes.rb
Rails.application.routes.draw do

  constraints user_agent: /Chrome/ do
    get "/" => "store#index"
  end

  constraints(-> (req) { req.env["HTTP_USER_AGENT"] !~ /Chrome/ }) do
    resources :ratings

    get 'my-orders' => 'users#orders'
    get 'my-items' => 'users#line_items'

    namespace :admin do
      get 'categories/show'
      get 'categories' => 'categories#index'
    end

    namespace :admin do
      post 'reports/show_orders'
      resources :reports
    end

    resources :subcategories

    get 'categories/all'
    resources :categories

    controller :sessions do
      get 'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
    end

    get 'sessions/new'

    get 'sessions/create'

    get 'sessions/destroy'

    get 'users/orders'
    get 'users/line_items'
    post 'users/show_line_items'
    resources :users

    resources :orders

    resources :line_items

    resources :carts

    get 'store/index'

    resources :books, controller: "products"
    resources :products do
      get :who_bought, on: :member
    end

    scope '(:locale)' do
      resources :orders
      resources :line_items
      resources :carts
      root 'store#index', as: 'store', via: :all
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include ActiveModel::Dirty

  has_one :address, dependent: :destroy
  accepts_nested_attributes_for :address

  has_many :ratings, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :line_items, dependent: :destroy

  after_create :send_welcome_mail  
  before_update :user_cannot_be_updated
  before_destroy :user_cannot_be_destroyed
  after_destroy :ensure_an_admin_remains

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :email, uniqueness: { case_sensitive: false }, format: {
    with: /\A[a-z0-9._-]+@[a-z0-9]+\.[a-z]{2,4}\z/i
  }
  has_secure_password
  
  private
    def send_welcome_mail
      WelcomeNewUser.created(self).deliver
    end

    def ensure_an_admin_remains
      if User.count.zero?
        errors.add(:base, "Can't delete last user")
        false
      end
    end

    def user_cannot_be_destroyed
      if email == 'admin@depot.com'
        errors.add(:base, "This user cannot be deleted!!!")
        false
      end
    end

    def user_cannot_be_updated
      if email_was == 'admin@depot.com'
        errors.add(:base, "This user cannot be updated!!!")
        false
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  layout "myorders", only: [:orders, :line_items]

  def orders
    @orders = User.find_by(id: session[:user_id]).orders
    @total = 0
    @orders.each do |order|
      order.line_items.each do |line_item|
        @total += line_item.product.price
      end
    end
  end

  def line_items
    @pagination_size = 4
    @current_user = User.find_by(id: session[:user_id])
    @line_items_count = @current_user.line_items.size
  end

  def show_line_items
    respond_to do |format|
      format.js
    end
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.order(:name)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    @user.build_address
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: "User #{@user.name} was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: "User #{@user.name} was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if @user.destroy
      flash[:notice] = "User #{@user.name} deleted"  
    else
      @user.errors.full_messages.each do |message|
        flash[:notice] = message
      end
    end
    
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :role, :password, :password_confirmation, :language, address_attributes:[:city, :state, :country, :pincode])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="depot_form">

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %>
        prohibited this user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
  <legend>Enter User Details</legend>
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name, size: 40, placeholder: 'Name'%>
    </div>
    <div class="field">
      <%= f.label :email %>
      <%= f.email_field :email, size: 40, placeholder: 'Email' %>
    </div>

    <%= f.fields_for :address do |address_form| %>
      <div class="field">
        <%= address_form.label :city %>
        <%= address_form.text_field :city, size: 40, placeholder: 'City' %>
      </div>
      <div class="field">
        <%= address_form.label :state %>
        <%= address_form.text_field :state, size: 40, placeholder: 'State' %>
      </div>
      <div class="field">
        <%= address_form.label :country %>
        <%= address_form.text_field :country, size: 40, placeholder: 'Country' %>
      </div>
      <div class="field">
        <%= address_form.label :pincode %>
        <%= address_form.text_field :pincode, size: 40, placeholder: 'Pincode' %>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :language %>
      <%= f.select :language, options_for_select(["english", "hindi"], "english") %>
    </div>

    <div class="field">
      <%= f.label :password %>
      <%= f.password_field :password, size: 40, placeholder: 'Password' %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, size: 40, placeholder: 'Confirm Password' %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  </fieldset>
<% end %>

</div>

app/views/users/_order.html.erb
<tr>
  <td><%= order.name %></td>
  <td><%= order.address %></td>
  <td><%= order.email %></td>
  <td><%= order.pay_type %></td>
  <td><%= order.created_at %></td>
  <td>
    <ul>
    <% amount = 0 %>
    <% order.line_items.each do |line_item| %>
    <% amount += line_item.product.price %>
      <li><%= line_item.product.title %></li>
    <% end %>
    </ul>
  </td>
  <td><%= number_to_currency(amount) %></td>
</tr>

app/views/users/_pagination.html.erb
<% offset_value = params[:size].to_i * (params[:pageNo].to_i - 1) %>

<table>
  <tr>
    <th>Line Item</th>
    <th>Created At</th>
  </tr>
  <% User.find_by(id: session[:user_id]).line_items.limit(params[:size]).offset(offset_value).each do |line_item| %>
    <tr>
      <td><%= line_item.product.title %></td>
      <td><%= line_item.created_at %></td>
    </tr>
  <% end %>
</table>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/line_items.html.erb
<% pageNo = 1 %>
<% pages = (@line_items_count.to_f / @pagination_size).ceil %>

<p> Total Line Items: <b><%= @line_items_count %></b> </p>
<p> Line Items per page: <b><%= @pagination_size %></b> </p>
<p> Total pages: <b><%= pages %></b> </p>

<div id='navigators'>
  <% while pageNo <= pages do %>
    <%= button_to pageNo, users_show_line_items_path({pageNo: pageNo, size: @pagination_size}), remote: true %>
    <% pageNo += 1 %>
  <% end %>
</div>

<div id='line_items_list'></div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/orders.html.erb
<h1>Your all orders till date</h1>
<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Email</th>
    <th>Payment Type</th>
    <th>Placed On</th>
    <th>Items</th>
    <th>Total Amount</th>
  </tr>
  <%= render partial: "order", collection: @orders %>
</table>

<p>Grand Total: <%= number_to_currency(@total) %></p>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
  <br>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/show_line_items.js.erb
$("#line_items_list").html("<%= escape_javascript render 'pagination' %>");