config/routes.rb
Rails.application.routes.draw do

  constraints user_agent: /Chrome/ do
    get "/" => "store#index"
  end

  constraints(-> (req) { req.env["HTTP_USER_AGENT"] !~ /Chrome/ }) do
    resources :ratings

    get 'my-orders' => 'users#orders'
    get 'my-items' => 'users#line_items'

    namespace :admin do
      get 'categories/show'
      get 'categories' => 'categories#index'
    end

    namespace :admin do
      post 'reports/show_orders'
      resources :reports
    end

    resources :subcategories

    get 'categories/all'
    resources :categories

    controller :sessions do
      get 'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
    end

    get 'sessions/new'

    get 'sessions/create'

    get 'sessions/destroy'

    get 'users/orders'
    get 'users/line_items'
    post 'users/show_line_items'
    resources :users

    resources :orders

    resources :line_items

    resources :carts

    get 'store/index'

    resources :books, controller: "products"
    resources :products do
      get :who_bought, on: :member
    end

    scope '(:locale)' do
      resources :orders
      resources :line_items
      resources :carts
      root 'store#index', as: 'store', via: :all
    end
  end
end

app/models/product.rb
class UrlValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /.(gif|jpg|jpeg|png)\Z/i
      record.errors[attribute] << 'must be a URL for GIF, JPG or PNG image.'
    end
  end
end

class PriceValidator < ActiveModel::Validator
  def validate(record)
    if record.price < record.discounted_price
      record.errors[:price] << 'should be greater than discount price'
    end
  end
end

class Product < ActiveRecord::Base
  include ActiveModel::Dirty
  
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, limit: 3
  
  has_many :ratings, dependent: :destroy
  has_many :line_items, dependent: :restrict_with_error
  has_many :orders, through: :line_items
  has_many :carts, through: :line_items
  belongs_to :category, polymorphic: true
  
  after_create :increment_counters
  after_destroy :decrement_counters
  after_update :adjust_counters
  before_save :assign_default_title, if: :is_title_blank?
  # before_save :set_discount_price, if: :is_discounted_price_blank?
  
  # validates :image_url, presence: true, url: true
  
  validates :permalink, uniqueness: { case_sensitive: false }, format: {
    with: /\A[a-z]+(\-[a-z]+){2,}\z/i,
    message: :invalid
  }
  validates :discounted_price, numericality: true, unless: :is_discounted_price_blank?
  validates :price, presence: true, numericality: {
    greater_than_or_equal_to: 0.01
  }
  validates :price, numericality: {
    greater_than: :discounted_price
  }, unless: :is_discounted_price_blank?
  validates :category_id, presence: true
  # validate :description_size

  # validates_with PriceValidator, unless: [:is_price_blank?, :is_discounted_price_blank?]

  # validates :images, presence: true

  scope :enabled, -> { where(enabled: true) }

  def self.latest
    Product.order(:updated_at).last
  end

  private
    def description_size
      word_count = description.split.length
      if word_count < 5 || word_count > 10
        errors.add(:description, :invalid)
      end
    end

    def is_title_blank?
      title.blank? ? true : false
    end

    def is_price_blank?
      price.blank? ? true : false
    end

    def is_discounted_price_blank?
      discounted_price.blank? ? true : false
    end

    def assign_default_title
      self.title = 'abc'
    end

    def set_discount_price
      self.discounted_price = price
    end

    def no_images_added(attributes)
      attributes[:url].blank?
    end

    [:increment, :decrement].each do |type|
      define_method("#{type}_counters") do
        category_type.constantize.send("#{type}_counter", :count, category_id)
        if category_type == 'Subcategory'
          'Category'.constantize.send("#{type}_counter", :count, Subcategory.find(category_id).category_id)
        end  
      end
    end

    def adjust_counters
      category_type_was.constantize.send(:decrement_counter, :count, category_id_was)
      if category_type_was == 'Subcategory'
        'Category'.constantize.send(:decrement_counter, :count, Subcategory.find(category_id_was).category_id)
      end
      increment_counters();
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :save_image, only: :create
  before_action :save_updated_image, only: :update

  before_action :set_locale
  after_action :reset_locale

  def who_bought
    @product = Product.find(params[:id])
    @latest_order = @product.orders.order(:updated_at).last
    if stale?(@latest_order)
      respond_to do |format|
        format.atom
      end
    end
  end

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    3.times { @product.images.build }
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: t('.notice') }
        format.json { render :show, status: :created, location: @product }
      else
        # 3.times { @product.images.build }
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params_without_images)
        format.html { redirect_to @product, notice: t('.notice') }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy

    if @product.errors.any?
      @product.errors.full_messages.each do |message|
        flash[:notice] = message
      end
    end
    
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price, :enabled, :discounted_price, :permalink, :category_id, :category_type, images_attributes: [:url, :product_id])
    end

    def product_params_without_images
      params.require(:product).permit(:title, :description, :image_url, :price, :enabled, :discounted_price, :permalink, :category_id, :category_type)
    end
    
    def save_image
      if(params[:product].has_key?(:images_attributes))
        images = params[:product][:images_attributes]
        uploaded_image1 = images["0"][:url] if images.has_key?("0")
        uploaded_image2 = images["1"][:url] if images.has_key?("1")
        uploaded_image3 = images["2"][:url] if images.has_key?("2")
                
        [uploaded_image1, uploaded_image2, uploaded_image3].each_with_index do |uploaded_image, index|
          unless uploaded_image.nil?
            File.open(Rails.root.join('app', 'assets', 'images', uploaded_image.original_filename), 'wb') do |file|
              file.write(uploaded_image.read)
            end
            images[index.to_s][:url] = uploaded_image.original_filename
          end
        end
      end
    end

    def save_updated_image
      @product.images.each_with_index do |image, index|
        unless params[:product][:images_attributes][index.to_s].blank?
          image.url = params[:product][:images_attributes][index.to_s][:url].original_filename
        end
      end
    end

    def set_locale
      if session[:user_id]
        language = User.find(session[:user_id]).language
        if language == 'hindi'
          I18n.locale = :hi
        else
          I18n.locale = :en
        end
      end
    end

    def reset_locale
      I18n.locale = :en
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  def setup_product(product)
    3.times { product.images.build }
    product
  end
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= t('activerecord.errors.template.header', count: @product.errors.size, model: @product.class) %></h2>    
 
      <ul>
        <% @product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :category_id %><br>
    <%= 
      f.select(
        :category_id, 
        Category.all.map{ |c| [c.name, c.id, {'data-type' => 'Category'}]} + 
        Subcategory.all.map{ |c| [c.name, c.id, {'data-type' => 'Subcategory'}]}, 
        { prompt: 'Select One' }, { :onchange => "set_category_type()" }
      )
    %>
  </div>

  <div class="field">
    <%= f.hidden_field :category_type %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, rows: 6, cols: 30, style: "resize: none" %>
  </div>

  <%= f.fields_for :images do |image| %>
    <% unless @product.images[image.index].url.nil? %>
      <% image_url = Rails.root.join('app', 'assets', 'images', @product.images[image.index].url) %>
    <% end %>
    <div class="field">
      <% if image_url && File.file?(image_url) %>
        <p class='details'><%= 'Update image ' %><b><%= image.index + 1 %></b> : <b><%= @product.images[image.index].url %></b></p>
        <%= image.file_field :url, accept: 'image/png,image/gif,image/jpeg' %>
      <% else %>
        <%= image.label :url, 'Upload Image' %>
        <%= image.file_field :url, accept: 'image/png,image/gif,image/jpeg' %>
      <% end %>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.check_box :enabled %>
    <%= f.label :enabled %><br>
  </div>
  <div class="field">
    <%= f.label :discounted_price %><br>
    <%= f.text_field :discounted_price %>
  </div>
  <div class="field">
    <%= f.label :permalink %><br>
    <%= f.text_field :permalink %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
  <% if product.images.present? %>
    <td class = 'product-images'>
      <% product.images.each do |image| %>
        <%= image_tag(image.url, class: 'list_image') %>
      <% end %>
    </td>
  <% else %>
    <td>No Image Available</td>
  <% end %>
  
  <% ratings_total = product.ratings.sum(:rate) %>
  <% if ratings_total > 0 %>
    <% ratings_count = product.ratings.count %>
    <% average_rating = ratings_total/ratings_count %>
  <% else %>
    <% average_rating = 0.0 %>
  <% end %>

  <td class="list_description">
    <dl>
      <dt><%= product.title %> (<%= average_rating.round(2) %>/5.0)</dt>
      <dd><%= pluralize(product.images.length, "image") %> available</dd>
      <dd>Category: <b><%= product.category.name %></b></dd>
      <dd><%= truncate(strip_tags(product.description), length: 80) %></dd>
    </dl>
  </td>
  <td class="list_actions">
    <%= link_to 'Show', product %><br/>
    <%= link_to 'Edit', edit_product_path(product) %><br/>
    <%= link_to 'Destroy', product, method: :delete, 
                data: { confirm: 'Are you sure?' } %><br/>
    <%= link_to 'Rate Product', new_rating_path(id: product.id) %><br/>
  </td>
</tr>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<h1>Listing products</h1>
<table>
  <%= render @products %>
</table>

<br>
<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Enabled:</strong>
  <%= @product.enabled %>
</p>

<p>
  <strong>Discount Price:</strong>
  <%= @product.discounted_price %>
</p>

<p>
  <strong>Permalink:</strong>
  <%= @product.permalink %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>